language: node_js
node_js:
  - "12.14"

script:
  - npm run test

before_deploy:
  - "echo 'ready to deploy?'"
  - npm run build

deploy:
  - provider: npm
    email: "$NPM_EMAIL"
    api_key: "$NPM_TOKEN"
    skip_cleanup: true
    on:
      tag: true

after_deploy:
- "echo 'deployed!'"
