language: node_js
node_js:
  - "12.14"

# @todo: check with arnold for the _key and _iv on openssl command 
#   - need to create a new github deploy key and see the output of `travis encrypt-file`
# before_install:
#   - >-
#     openssl aes-256-cbc 
#     -K $encrypted_xxxxxxxxxxxx_key 
#     -iv $encrypted_xxxxxxxxxxxx_iv 
#     -in github_deploy_key.enc 
#     -out github_deploy_key 
#     -d
#   - chmod 600 github_deploy_key
#   - eval $(ssh-agent -s)
#   - ssh-add github_deploy_key

jobs:
  include:
    - stage: Test
      script: 
        - npm run test

    - stage: Version
      # if: tag IS NOT present AND branch = master
      if: tag IS NOT present
      script: 
        - npm version patch
        - git push --tags

    - stage: Release
      # if: tag IS present AND branch = master
      if: tag IS present
      script: npm run build
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_token: $NPM_TOKEN
        cleanup: false
        dry_run: true # @todo: remove once we know it works
        on:
          tags: true
