language: node_js
node_js:
  - "12.14"

jobs:
  include:
    - stage: Test
      script: 
        - npm run test

    - stage: Version
      # if: tag IS NOT present AND branch = master
      if: tag IS NOT present
      script: ./scripts/version.sh

    - stage: Release
      # if: tag IS present AND branch = master
      if: tag IS present
      script: npm run build
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_token: $NPM_TOKEN
        cleanup: false
        dry_run: true
        on:
          tags: true
