language: node_js
node_js:
  - "12.14"

# jobs:
#   include:
#     - stage: test
#       script: 
#         - echo "Running test script ..."
#         - npm run test

#     - stage: version
#       script: ./scripts/version.sh
#         on:
#           tags: false
#           branch: master

#     - stage: release
#       script: 
#         - echo "Running release script ..."
#       deploy:
#         provider: npm
#         email: $NPM_EMAIL
#         api_token: "SHOULD FAIL"
#         on: 
#           tags: true
#           # branch: master
